# All Rights Reserved
# Copyright (c) 2023 Nyria
#
# This code, including all accompanying software, documentation, and related materials, is the exclusive property
# of Nyria. All rights are reserved.
#
# Any use, reproduction, distribution, or modification of the code without the express written
# permission of Nyria is strictly prohibited.
#
# No warranty is provided for the code, and Nyria shall not be liable for any claims, damages,
# or other liability arising from the use or inability to use the code.

services:

# ------------------------- Redis ----------------------------- #

  redis:
    container_name: redis

    image: redis

    cpus: 1
    mem_limit: 1G
    restart: unless-stopped

    ports:
      - 6379:6379

    volumes:
      - redis-data:/data
    tty: true

    command:
      - redis-server
      - --save 60 1
      - --loglevel notice

    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5

# ------------------------- MariaDB ----------------------------- #

  mariadb:
    container_name: mariadb

    image: mariadb

    cpus: 1
    mem_limit: 3G
    restart: unless-stopped

    ports:
      - 3306:3306

    volumes:
      - mariadb-data:/var/lib/mysql
    tty: true

    environment:
      MYSQL_ROOT_PASSWORD: Test123
      MYSQL_DATABASE: nyria
      MYSQL_USER: root
      MYSQL_PASSWORD: Test123

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 5

# ------------------------- LavaLink ----------------------------- #

  lavalink:
    container_name: lavalink

    build:
      context: lavalink
      dockerfile: Dockerfile

    cpus: 1
    mem_limit: 1G
    restart: unless-stopped

    ports:
      - 2333:2333

    volumes:
      - lavalink-data:/lavalink/logs

# ------------------------- Nyria Bot ----------------------------- #

  nyria-bot:
    container_name: nyria-bot

    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
      lavalink:
        condition: service_started

    build:
      context: nyriaBot
      dockerfile: Dockerfile

    cpus: 1
    mem_limit: 8G
    restart: unless-stopped

    ports:
      - 1384:1384

    links:
      - "mariadb:db"

# ------------------------- Volumes ----------------------------- #

volumes:
  redis-data:
  mariadb-data:
  lavalink-data:
