# All Rights Reserved
# Copyright (c) 2023 Nyria
#
# This code, including all accompanying software, documentation, and related materials, is the exclusive property
# of Nyria. All rights are reserved.
#
# Any use, reproduction, distribution, or modification of the code without the express written
# permission of Nyria is strictly prohibited.
#
# No warranty is provided for the code, and Nyria shall not be liable for any claims, damages,
# or other liability arising from the use or inability to use the code.

services:

# ------------------------- Redis ----------------------------- #

  redis:
    container_name: redis
    image: redis

    cpus: 1
    mem_limit: 1G
    restart: unless-stopped

    ports:
      - 6379:6379

    volumes:
      - redis-data:/data
    tty: true

    command:
      - redis-server
      - --save 60 1
      - --loglevel notice

    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5

    networks:
        - nyria

# ------------------------- MariaDB ----------------------------- #

  mariadb:
    container_name: mariadb
    image: mariadb

    cpus: 1
    mem_limit: 3G
    restart: unless-stopped

    ports:
      - 3306:3306

    volumes:
      - mariadb-data:/var/lib/mysql
    tty: true

    environment:
      MYSQL_ROOT_PASSWORD: Test123
      MYSQL_DATABASE: nyria
      MYSQL_USER: root
      MYSQL_PASSWORD: Test123

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 1s
      timeout: 3s
      retries: 5

    networks:
      - nyria

# ------------------------- LavaLink ----------------------------- #

  lavalink:
    container_name: lavalink
    build:
      context: lavalink
      dockerfile: Dockerfile

    cpus: 1
    mem_limit: 1G
    restart: unless-stopped

    ports:
      - 2333:2333

    volumes:
      - lavalink-data:/lavalink/logs

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2333/"]
      interval: 1s
      timeout: 3s
      retries: 5

    networks:
      - nyria

# ------------------------- Nyria Bot ----------------------------- #

  nyria-bot:
    container_name: nyria-bot
    depends_on:
      lavalink:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

    build:
      context: nyriaBot
      dockerfile: Dockerfile

    ports:
      - 1384:1384

    restart: unless-stopped

# ------------------------- Volumes ----------------------------- #

volumes:
  redis-data:
  mariadb-data:
  lavalink-data:

# ------------------------- Network ----------------------------- #

networks:
  nyria:
    name: nyria
